### ISSUE TITLE
Package not working with solid starter template

### ISSUE THREAD

**Issue by eulervoid** [tahti-studio/solid-knobs#5]
Hello,
the package looks very nice and just like what i currently need, but i had some problems when trying to use it. 
Even in the most basic solid app i get a strange error that says `Uncaught ReferenceError: React is not defined` as soon as i try to instantiate a `<Control>` Component. This is a mystery to me as nowhere in the project react is used. The error is then pointing to a tsx file that does not exist: `Could not load content for http://localhost:5173/node_modules/solid-knobs/src/Control.tsx` – the folder in question just contains a `dist` directory with code in it, no `src`.
I briefly tried to look into it myself, but quickly found out that i have no idea how npm packages are actually built and distributed. 

Steps to reproduce:
1. Create a new solid app with: `npx degit solidjs/templates/ts solid-knobs-test-app`
2. `cd solid-knobs-test-app && npm install solid-knobs`
4. Add import `import { Control } from "solid-knobs"` in App.tsx
5. Add a minimal `<Control range={...} ...>...</Control>` component
6. Run `npm run dev`

**Comment by httnn** [comment]
hey @eulervoid, thanks for the report and detailed repro steps! i'll take a deeper look at this next week.

**Comment by httnn** [comment]
this should now be fixed in v0.3.1

the issue was that i wasn't using a proper bundler to build the distributed code which resulted in there still being JSX instead of transpiled JS. most bundlers don't transpile stuff in node_modules by default which is where the error you experienced came from.

thanks for the report, @eulervoid!
